- .gitignore
- source/content/pages/02-learning-python/05-emacs.markdown
Hello. I need to say that my English is really poor. Take extra attintion to your review.
Thanks.
> Emacs article.

- source/content/pages/06-web-apis/03-api-creation.markdown
Falcon seems more suited for REST development than full-stack web development. Pycnic is designed from the ground up for JSON APIs.
> Added Falcon and Pycnic to the list.

- source/content/pages/07-web-app-deployment/15-monitoring.markdown
Hello. Is adding the change to the Markdown sufficient? Or do I also need to rebuild the html?
> Add Opbeat to list of hosted monitoring services.

- all.html
- application-dependencies.html
- development-environments.html
- operating-systems.html
- source/content/pages/02-development-environments/01-development-environments.markdown
- source/content/pages/07-web-app-deployment/05-operating-systems.markdown
- source/content/pages/07-web-app-deployment/09-app-dependencies.markdown
Change  virtualenv URL from http://www.virtualenv.org/en/latest/ to http://www.virtualenv.org/en/latest/
> change all virtualenv url to http://www.virtualenv.org/en/latest/

- all.html
- source/content/pages/02-development-environments/03-vim.markdown
- vim.html
Removed the redundant word "used".
> fix a typo on vim page

- all.html
- source/content/pages/04-web-development/16-static-site-generator.markdown
- static-site-generator.html
What's the downside to using static site generators?  --> What's the downside of using static site generators?
> fix typo on page static site generators

- all.html
- jinja2.html
- source/content/pages/04-web-development/17-jinja2.markdown
can be used a -> can be used as a
> fix typo on page jinja2.markdown

- all.html
- no-sql-datastore.html
- source/content/pages/05-data/03-nosql.markdown
'A the column-family table' --> 'A column-family table'
> fix typo on page nosql

- source/content/pages/07-web-development/21-task-queues.markdown
Feel free to reject if you don't want it to be listed.
> add Kuyruk to the projects list

- content/pages/08-web-app-deployment/36-aws-lambda.markdown
> added an aws lambda resource

- content/pages/07-web-development/26-task-queues.markdown
- content/pages/07-web-development/40-dramatiq.markdown
- theme/templates/choices/dramatiq.html
- theme/templates/table-of-contents.html
This adds some sections on [Dramatiq](https://dramatiq.io).  I mostly looked at the sections for Celery and RQ and set up things in a similar way.  Let me know if I missed anything or if you'd like me to change anything. Thanks!
> add Dramatiq

- .vscode/settings.json
i found having this in my local checkout useful, since i use Microsoft VisualStudio Code as my preferred editor, and i think any other that might contribute and also prefer this editor will find it useful too.
the `.vscode` directory is known as workspace settings and has been designed to only store project settings that are meant to be distributed with the source code. the editor has a concept of user settings and global settings that can be used to in addition to workspace settings. its not a super verbose XML based project definition with random UUIDs everywhere, its meant to be readable and hand editable, and its now considered best practice to check them in.
> vscode dotfiles for project-specific style settings

- content/pages/11-devops/02-monitoring.markdown
The current list of opensource and hosted monitoring tools has a great selection, but it can be a bit confusing knowing the focus area of each tool. I've categorized the existing tools (did not change the actual tools listed) to make it a bit easier to understand the speciality area of each tool.
> Categorize monitoring tools

- CONTRIBUTING.rst
> There is not "source" folder which contains requirements.txt

- theme/templates/sponsor/scout.html
> Couple of tweaks to Scout sponsor text

- content/pages/02-development-environments/06-jupyter-notebook.markdown
- content/pages/02-development-environments/14-pymux.markdown
- content/pages/02-development-environments/20-source-control.markdown
- content/pages/03-data/02-postgresql.markdown
- content/pages/03-data/04-sqlite.markdown
- content/pages/03-data/21-bokeh.markdown
- content/pages/04-web-development/02-django.markdown
- content/pages/04-web-development/03-flask.markdown
- content/pages/04-web-development/05-pyramid.markdown
- content/pages/04-web-development/31-rq-redis-queue.markdown
- content/pages/04-web-development/63-web-app-security.markdown
- content/pages/05-deployment/19-nginx.markdown
- content/pages/05-deployment/23-gunicorn.markdown
- content/posts/170214-create-ssh-keys-ubuntu.markdown
- content/posts/180420-monitor-aws-lambda-python-3-6.markdown
Here are the urls I fixed from here: https://github.com/mattmakai/fullstackpython.com/pull/166
> Fix bad urls

- content/pages/02-development-environments/21-git.markdown
Referenced in https://www.fullstackpython.com/future-directions.html:
Git: Add "why use git?", "what is a distributed version control system?", "what's the difference between git and github?" and "git clients" sections.
> Add content for why git

- content/pages/06-devops/00-devops.markdown
> a typo fixed

- content/pages/03-data/06-sqlalchemy.markdown
Adding an SQLAlchemy resource. Kindly accept the pull request.
> Adding a SQLAlchemy resource.

- content/pages/05-deployment/36-docker.markdown
> adds a django and docker resource

- check_urls.py
Added support for up to 10 retries for a given HTTP session. This wipes out a handful of false positives during the url testing phase.
> Add support for request retries

- check_urls.py
This pull request was part of the [next steps that I intended to make from my blog post](https://www.twilio.com/blog/2018/07/find-fix-website-link-rot-python-beautifulsoup-requests.html). Finally got around to it! It looks like this:
```
usage: check_urls.py [-h] [-timeout TIMEOUT] [-retries RETRIES]
[-threads THREADS]
Check correctness of url links.
optional arguments:
-h, --help            show this help message and exit
-timeout TIMEOUT, --url-timeout TIMEOUT
Timeout in seconds to wait for url
-retries RETRIES, --url-retries RETRIES
Number of url retries
-threads THREADS, --num-threads THREADS
Number of threads to run with
```
> Add support for argparse

- content/pages/04-web-development/01-web-frameworks.markdown
> fix: minor typo

- content/posts/160518-install-postgresql-python-3-ubuntu-1604.markdown
Needed to add conn.commit() to save the table else when you go to view the table in a db manager it will not exist.Also added a conn.close() to close out the connection after creating the table or inserting new data
> Added conn.commit() to actually save the table in the db

- content/pages/04-web-development/03-flask.markdown
This project was moved into the group `cookiecutter-flask`.
> Update link for cookiecutter-flask project

- content/pages/03-data/04-sqlite.markdown
Added extendsclass.com, an online SQLite browser in section "Useful SQLite tools and code"
> Added an online SQLite browser

- content/pages/05-deployment/03-static-content.markdown
> add static content resource

- requirements.txt
[Click here](https://github.com/huangsam/fullstackpython.com/commit/021065119d1bd1ad8c063df9684ccfa51376bb40) for context.
> Update requests versioning
