mattmakai/fullstackpython.com

source/content/pages/04-web-development/02-django.markdown

Two Scoops of Django 1.8 was released.
this pull-request upgrade all references of Two Scoops of Django 1.6 to Two Scoops of Django 1.8
Two Scoops of Django 1.6 is now deprecated by the authors: 
http://twoscoopspress.org/pages/current-django-books
c/c @makaimc

upgrade to new version of Two Scoops of Django

---

source/content/posts/160619-pyramid-gunicorn-ubuntu-1604.markdown

Thank you for the write-up! Following are my suggestions for corrections.
- Pin version of Pyramid to 1.7, else pip will install the latest release on PyPI. This will future-proof your instructions and make them consistent with your Required Tools.
- virtualenv and pip do not need to be installed with Python 3.5 because it now includes venv and pip. You do, however, need to update both. You'll need to update your PNG, though.
- Use `python3 -m venv` to create a virtual environment, as this is now the recommended way, although it is not yet documented, per https://bugs.python.org/issue27285
- Use proper term for a Python virtual environment. venv, virtualenv, and pyvenv (which is merely a script that wraps venv) are all implementations of a virtual environment.
- Use official, canonical …

Corrections to instructions, terminology, and docs link

---

source/content/pages/07-web-app-deployment/14-logging.markdown

Thanks for the useful project by the way.

Update dead links in file 14-logging.markdown.

---

source/content/pages/09-data/12-nosql.markdown

sorry, atom removes the space at the end of the line
new addition:
```
* [Introduction to MongoDB and Python](https://realpython.com/blog/python/introduction-to-mongodb-and-python/) shows how to use Python to interface with MongoDB via PyMongo and MongoEngine.
```

added resource to nosql article

---

source/theme/templates/table-of-contents.html

A closing tag on Apache Cassandra link was missing and has been added.
Signed-off-by: Matthieu Berjon <matthieu@berjon.net>

Fixes table-of-contents.html closing tag

---

content/pages/07-web-development/34-pelican.markdown

Pelican uses the AGPL license, not GPL.

Fix license information for Pelican.

---

content/posts/160518-install-postgresql-python-3-ubuntu-1604.markdown

Without the database name, the psql command returns: `psql: FATAL:  database "matt" does not exist.` The required command is "psql testpython", as shown (subtly) in the image below the edited line.

Add db name to psql command

---

.gitignore
check_urls.py
requirements.txt

Here is the output that comes from the `check_urls.py` script: [urlout.txt](https://github.com/mattmakai/fullstackpython.com/files/1623544/urlout.txt)
This solution uses [ThreadPoolExecutor](https://docs.python.org/3.6/library/concurrent.futures.html) to resolve the inherent I/O bottleneck of URL requests. Also uses a fairly comprehensive regular expression for matching URLs. The pattern can be tweaked in the future if needed.

Add health check for urls

---

content/posts/160604-build-first-slack-bot-python.markdown

the greedy matching would result in the wrong mention parsing if another formatted link was in the message. this change makes it non-greedy.
fixes #150

makes username regex capture group non-greedy, fixes #150

---

content/pages/02-development-environments/03-vim.markdown

Remove 'Why Atom Can't Replace Vim' link and description

Remove duplicated link

---

.gitignore
check_urls.py

The previous implementation used Linux regular expressions. This was sufficient as a MVP but it was not accurate enough for corner cases. After doing some more research, it seemed as if using a HTML parsing library would be more efficient for this purpose. As such, the shell command has been scrapped away in favor of a more elaborate approach for detecting urls.
- Implement skeleton for extract_urls
- Detect html and markdown files
- Use bs4 for parsing html
- Convert markdown for bs4 parsing
- Remove use of urlin.txt and urlout.txt
- Remove unnecessary global vars

Improve url detection

---

content/pages/02-development-environments/14-pymux.markdown
content/pages/03-data/01-databases.markdown
content/pages/03-data/02-postgresql.markdown
content/pages/03-data/03-mysql.markdown
content/pages/03-data/05-object-relational-mappers.markdown
content/pages/03-data/06-sqlalchemy.markdown
content/pages/04-web-development/02-django.markdown
content/pages/04-web-development/11-template-engines.markdown
content/pages/04-web-development/42-code-metrics.markdown
content/pages/04-web-development/55-api-creation.markdown
content/posts/160510-flask-gunicorn-ubuntu-1604.markdown
content/posts/160511-send-sms-text-message-python.markdown
content/posts/160513-bottle-gunicorn-ubuntu-1604.markdown
content/posts/160515-sending-mms-picture-messages-python.markdown
content/posts/160518-install-postgresql-python-3-ubuntu-1604.markdown
content/posts/160530-respond-sms-text-messages-python-flask.markdown
content/posts/160605-reply-sms-python-bottle.markdown
content/posts/160830-phone-calls-bottle.markdown
content/posts/161123-make-phone-calls.markdown
content/posts/170723-monitor-flask-apps.markdown
content/posts/180202-monitor-django-web-apps.markdown
content/posts/180519-django-maps-mapbox.markdown

https://pypi.python.org now redirects to https://pypi.org/ - this pull request changes PyPi URLs to reflect the new hostname to avoid redirects from https://pypi.python.org.

Update pypi links with new hostname

---

content/pages/03-data/16-data-analysis.markdown

Looks like they removed the 'blog' prefix and changed to https.

Fix broken links to data exploration blog posts

---

content/pages/04-web-development/35-pelican.markdown

The site linked in the second bullet of the Pelican resources section seems to have become a link farm.

Remove linkrot from Pelican resources section

---

content/posts/170214-create-ssh-keys-ubuntu.markdown

I found your guide on generating SSH keys (https://www.fullstackpython.com/blog/ssh-keys-ubuntu-linux.html) after looking at the top 20 Google results for 'how do I generate an ssh key', and it looks like your default suggestions for using ssh-keygen are insecure.
I highly recommend you add this to your guide's ssh-keygen arguments:
ssh-keygen -o
(Note: The -o option was added in 2014; if this command fails for you, simply remove the -o option)
This will ensure the key is password-encrypted properly.
From the ssh-keygen manual:
-o      Causes ssh-keygen to save private keys using the new OpenSSH for‐
mat rather than the more compatible PEM format.  The new format
has increased resistance to brute-force password cracking but is
not supported by versions of OpenSSH prior to 6.5.  Ed25519 …

Secure the password encryption of ssh key

---

content/posts/160604-build-first-slack-bot-python.markdown

Adding additional notes section to mention about possible issue with SSL certificate. There are already some issues reported [python-slackclient](https://github.com/slackapi/python-slackclient/issues/334) and [websocket-client](https://github.com/websocket-client/websocket-client/issues/451).
Include a couple of suggestions, as part of the original post but I actually fixed the issue following the second one (Downloading the DigiCert and adding the env variable).
Issue #185 
_PS. Hey @mattmakai, no sure if this is the kind of fix you had in mind, if it isn't let me know and I'll try to follow up accordingly. Thanks!_

Slack Bot SSL Issue

---

check_urls.py

New output:
```
Extract urls...
Currently checking: file=19-nginx.markdown                                          
Check urls...
Currently checking: id=3057 host=www.airport-parking-shop.co.uk              
Bad url status: {
"http://www.codecademy.com/tracks/python": 404,
"http://sircmpwn.github.io/2017/01/13/The-problem-with-Python-3.html": 404,
"http://pythonforengineers.com/there-isnt-really-a-python-2-vs-python-3-problem/": 404,
"http://ryanfrantz.com/posts/solving-monitoring/": 404,
"http://hginit.com/": -1,
"https://devup.co/a-look-at-devops-tools-landscape-7220099c6b81": -1,
"https://blogs.msdn.microsoft.com/commandline/2018/06/20/windows-command-line-backgrounder/": 504,
"https://github.com/rosarior/awesome-django": 404,
"https://testdriven.io/part-one-flask-blueprints": 404, …
```

Add support for bad url locations

---

content/pages/01-introduction/02-python-programming-language.markdown
content/pages/02-development-environments/03-emacs.markdown
content/pages/02-development-environments/06-jupyter-notebook.markdown
content/pages/03-data/08-django-orm.markdown
content/pages/04-web-development/02-django.markdown
content/pages/04-web-development/26-angular.markdown
content/pages/04-web-development/36-unit-testing.markdown
content/pages/05-deployment/07-digitalocean.markdown
content/pages/06-devops/00-devops.markdown

Here are some more links that I found. Feel free to review them over again before approving the request. Some notable ones:
- The tern.js doesn't seem to have Django support anymore (at least the `tern_django` GitHub repo is down for good)
- There was an outdated link to a DigitalOcean discount. Not sure whether the link path is deprecated or that the discount is no longer applicable

Remove broken links from repo

---

content/pages/01-introduction/04-python-2-or-3.markdown
content/pages/04-web-development/27-task-queues.markdown
content/pages/04-web-development/45-microservices.markdown
content/pages/06-devops/18-web-analytics.markdown

Linkerd seem to have taken down one of its articles. Furthermore, some S3 bucket content has been invalidated. Not too many links to clean up this time around, so that's a good sign.

Remove bad links from content via check_urls

---

content/pages/01-introduction/10-best-python-podcasts.markdown

This adds a link to [The Real Python Podcast](https://realpython.com/podcasts/rpp/) to the podcasts list. Thanks for considering it! :)

Add Real Python Podcast to podcast list
